%% Set formatting style
list_factory = fieldnames(get(groot,'factory'));
index_interpreter = find(contains(list_factory,'Interpreter'));
for i = 1:length(index_interpreter)
    default_name = strrep(list_factory{index_interpreter(i)},'factory','default');
    set(groot, default_name,'latex');
end

%% input data
% timing
dt = 5/60; % time step, h
tSpan = (datetime(2020,1,1,0,0,0):hours(dt):datetime(2020,12,31,23,0,0))'; % time span as datetime
K = length(tSpan); % number of time steps
t = (0:dt:K*dt)';

% parameters
pRated = 72193; %Rated power required by Ammonia facility (kW)
pWind = simulateWind; %Power generated by a single 2MW Wind Turbine
uCost = 0.05; %Electricity cost per kWh for industry
wCapex = 2400000; %Investment cost of a 2MW Wind Turbine
wOpex = 80000; %Annual operating cost of 2MW Wind Turbine (using $40/kW/yr)
maxW = 150;
ylife = 25; %Facility lifespan
turbines = 0:1:maxW;
uCosts = 0.03:0.01:0.10;
optim_wt = zeros(1, 8);
optim_eCost = zeros(1, 8);
total_eGrid = zeros(1, maxW+1);
total_cost = zeros(1, maxW+1);
total_eWind = zeros(1, maxW+1);
eCost = zeros(1, maxW+1);
eCost(1,1) = uCost;
total_eGrid(1,1) = pRated*ylife*365*24;
total_energy = total_eGrid(1,1);
total_eWind(1,1) = 0;
total_cost(1,1) = total_energy*uCost;

%% Wind Model 1: Varying wind generators
for nWind = 1:1:maxW
    pGrid = pRated - nWind*pWind;
    pGrid = max(pGrid, 0); % Ensures no negative grid power
    total_eGrid(1,nWind+1) = sum(pGrid)*dt*ylife;
    total_eWind(1,nWind+1) = sum(pWind)*dt*ylife*nWind;
    total_cost(1,nWind+1) = sum(pGrid)*dt*ylife*uCost + nWind*(wCapex + wOpex*ylife);
    eCost(1,nWind+1) = total_cost(1,nWind+1) / total_energy;
end

%% Wind Model for varying electricity costs
for k = 1:1:8
    uCost2 = uCosts(1,k);
    pGrid2 = zeros(1,K);
    eCost2 = zeros(1,maxW+1);
    total_eGrid2 = zeros(1, maxW+1);
    total_eWind2 = zeros(1, maxW+1);
    total_cost2 = zeros(1, maxW+1);
    eCost2(1,1) = uCost2;
    total_eGrid2(1,1) = pRated*ylife*365*24;
    total_energy2 = total_eGrid2(1,1);
    total_eWind2(1,1) = 0;
    total_cost2(1,1) = total_energy2*uCost2;
    for nWind2 = 1:1:maxW
        pGrid2 = pRated - nWind2*pWind;
        pGrid2 = max(pGrid2, 0); % Ensures no negative grid power
        total_eGrid2(1,nWind2+1) = sum(pGrid2)*dt*ylife;
        total_eWind2(1,nWind2+1) = sum(pWind)*dt*ylife*nWind2;
        total_cost2(1,nWind2+1) = sum(pGrid2)*dt*ylife*uCost2 + nWind2*(wCapex + wOpex*ylife);
        eCost2(1,nWind2+1) = total_cost2(1,nWind2+1) / total_energy2;
    end
    optim_eCost = min(eCost2);
    optim_wt(1,k) = find(eCost2(1:end) == optim_eCost, 1, "first" ) - 1;
end
grid_percent = (total_eGrid)./(total_eGrid+total_eWind);

%% plot
figure;
yyaxis left
plot(turbines'*2,eCost*1000, '-', 'LineWidth', 1.5);
grid on
xlabel({'Wind Farm Capacity [MW]'}, 'FontSize', 12);
xlim([0 maxW*2])
ylabel({'Electricity Cost [\$/MWh]'},'FontSize', 12)
title('Cost of electricity with Wind Turbines', 'FontSize', 14)
hold on;
yyaxis right
plot(turbines'*2,total_cost / 1000000 / ylife, 'r-', 'LineWidth', 1.5);
ylabel('Annual Electricity Cost [Million USD]','FontSize', 12);
legend({'Electricity Cost', 'Annual Cost'}, 'Location', 'Best');

figure;
plot(turbines'*2,total_eGrid / 1000000000 / ylife, 'r-', 'LineWidth', 1.5); hold on;
plot(turbines'*2,total_eWind / 1000000000 / ylife, 'b-', 'LineWidth', 1.5);
grid on
xlabel({'Wind Farm Capacity [MW]'}, 'FontSize', 12);
xlim([0 maxW*2])
ylabel('Annual Energy Consumption [TWh]','FontSize', 12)
legend({'Energy from Grid', 'Energy from Wind'}, 'Location', 'Best');
title('Energy Sourcing', 'FontSize', 14);

figure;
plot(uCosts'*1000,optim_wt*2, 'r-', 'LineWidth', 1.5);
grid on
xlabel('Average Electricity Cost [\$/MWh]', 'FontSize', 12);
ylabel('Optimal Wind Farm Capacity [MW]','FontSize', 12)
title('Optimization of Wind Farm', 'FontSize', 14);