function [windSpeed80m,windSpeed100m,windSpeed120m,offsetGMT] = importWind(fileName,t)
% importWeather imports and processes weather data from a CSV file
% generated by OikoLab.
%
% Input:
%   fileName, the name of the OikoLab CSV weather file.
%   t, the datetime span.
%
% Output:
%   temperature, the outdoor temperature in C
%   totalHorizontal, the total solar shortwave irradiance on a horizontal surface in kW/m^2
%   beamNormal, the beam solar shortwave irradiance on a normal surface in kW/m^2
%   diffuseHorizontal, the diffuse solar shortwave irradiance on a horizontal surface in kW/m^2
%   offsetGMT, (local time) - (Greenwich mean time) in hours

% import raw data
opts = detectImportOptions(fileName);
opts.PreserveVariableNames = 1;
windData = readtable(fileName,opts);

% create a datetime array
date = datetime(windData.Year, windData.Month, windData.Day, windData.Hour, windData.Minute, 0);

% extract wind speeds
windSpeed100m = windData{:,6};
windSpeed80m = windData{:,7};
windSpeed120m = windData{:,8};
windSpeed100m = round(windSpeed100m, 2);
windSpeed80m = round(windSpeed80m, 2);
windSpeed120m = round(windSpeed120m, 2);

offsetGMT = 0;
dateET = date + hours(offsetGMT); % convert UTC to eastern

% pack the data into a timetable object
TT = timetable(dateET,...
    windSpeed80m,windSpeed100m,windSpeed120m);

% retime to the desired time steps
TT = retime(TT,t);
windSpeed80m = TT{:,1};
windSpeed100m = TT{:,2};
windSpeed120m = TT{:,3};

end

